package com.bacuti.domain;

import static com.bacuti.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MachineUsageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUsageAllPropertiesEquals(MachineUsage expected, MachineUsage actual) {
        assertMachineUsageAutoGeneratedPropertiesEquals(expected, actual);
        assertMachineUsageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUsageAllUpdatablePropertiesEquals(MachineUsage expected, MachineUsage actual) {
        assertMachineUsageUpdatableFieldsEquals(expected, actual);
        assertMachineUsageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUsageAutoGeneratedPropertiesEquals(MachineUsage expected, MachineUsage actual) {
        assertThat(expected)
            .as("Verify MachineUsage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUsageUpdatableFieldsEquals(MachineUsage expected, MachineUsage actual) {
        assertThat(expected)
            .as("Verify MachineUsage relevant properties")
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getUsage()).as("check usage").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getUsage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUsageUpdatableRelationshipsEquals(MachineUsage expected, MachineUsage actual) {
        assertThat(expected)
            .as("Verify MachineUsage relationships")
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getSite()).as("check site").isEqualTo(actual.getSite()))
            .satisfies(e -> assertThat(e.getUnitOfMeasure()).as("check unitOfMeasure").isEqualTo(actual.getUnitOfMeasure()));
    }
}
