package com.bacuti.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MachineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineAllPropertiesEquals(Machine expected, Machine actual) {
        assertMachineAutoGeneratedPropertiesEquals(expected, actual);
        assertMachineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineAllUpdatablePropertiesEquals(Machine expected, Machine actual) {
        assertMachineUpdatableFieldsEquals(expected, actual);
        assertMachineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineAutoGeneratedPropertiesEquals(Machine expected, Machine actual) {
        assertThat(expected)
            .as("Verify Machine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUpdatableFieldsEquals(Machine expected, Machine actual) {
        assertThat(expected)
            .as("Verify Machine relevant properties")
            .satisfies(e -> assertThat(e.getMachineName()).as("check machineName").isEqualTo(actual.getMachineName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUpdatableRelationshipsEquals(Machine expected, Machine actual) {
        assertThat(expected)
            .as("Verify Machine relationships")
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getRouting()).as("check routing").isEqualTo(actual.getRouting()));
    }
}
