package com.bacuti.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentLaneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentLaneAllPropertiesEquals(ShipmentLane expected, ShipmentLane actual) {
        assertShipmentLaneAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentLaneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentLaneAllUpdatablePropertiesEquals(ShipmentLane expected, ShipmentLane actual) {
        assertShipmentLaneUpdatableFieldsEquals(expected, actual);
        assertShipmentLaneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentLaneAutoGeneratedPropertiesEquals(ShipmentLane expected, ShipmentLane actual) {
        assertThat(expected)
            .as("Verify ShipmentLane auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentLaneUpdatableFieldsEquals(ShipmentLane expected, ShipmentLane actual) {
        assertThat(expected)
            .as("Verify ShipmentLane relevant properties")
            .satisfies(e -> assertThat(e.getLane()).as("check lane").isEqualTo(actual.getLane()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentLaneUpdatableRelationshipsEquals(ShipmentLane expected, ShipmentLane actual) {
        assertThat(expected)
            .as("Verify ShipmentLane relationships")
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()));
    }
}
