package com.bacuti.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SiteFinishedGoodAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteFinishedGoodAllPropertiesEquals(SiteFinishedGood expected, SiteFinishedGood actual) {
        assertSiteFinishedGoodAutoGeneratedPropertiesEquals(expected, actual);
        assertSiteFinishedGoodAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteFinishedGoodAllUpdatablePropertiesEquals(SiteFinishedGood expected, SiteFinishedGood actual) {
        assertSiteFinishedGoodUpdatableFieldsEquals(expected, actual);
        assertSiteFinishedGoodUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteFinishedGoodAutoGeneratedPropertiesEquals(SiteFinishedGood expected, SiteFinishedGood actual) {
        assertThat(expected)
            .as("Verify SiteFinishedGood auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteFinishedGoodUpdatableFieldsEquals(SiteFinishedGood expected, SiteFinishedGood actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteFinishedGoodUpdatableRelationshipsEquals(SiteFinishedGood expected, SiteFinishedGood actual) {
        assertThat(expected)
            .as("Verify SiteFinishedGood relationships")
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getSite()).as("check site").isEqualTo(actual.getSite()))
            .satisfies(e -> assertThat(e.getFinishedGood()).as("check finishedGood").isEqualTo(actual.getFinishedGood()));
    }
}
