package com.bacuti.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UnitOfMeasureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnitOfMeasureAllPropertiesEquals(UnitOfMeasure expected, UnitOfMeasure actual) {
        assertUnitOfMeasureAutoGeneratedPropertiesEquals(expected, actual);
        assertUnitOfMeasureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnitOfMeasureAllUpdatablePropertiesEquals(UnitOfMeasure expected, UnitOfMeasure actual) {
        assertUnitOfMeasureUpdatableFieldsEquals(expected, actual);
        assertUnitOfMeasureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnitOfMeasureAutoGeneratedPropertiesEquals(UnitOfMeasure expected, UnitOfMeasure actual) {
        assertThat(expected)
            .as("Verify UnitOfMeasure auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnitOfMeasureUpdatableFieldsEquals(UnitOfMeasure expected, UnitOfMeasure actual) {
        assertThat(expected)
            .as("Verify UnitOfMeasure relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getKey()).as("check key").isEqualTo(actual.getKey()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnitOfMeasureUpdatableRelationshipsEquals(UnitOfMeasure expected, UnitOfMeasure actual) {}
}
