name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  ENVNAME: dev

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      commit_id: ${{ steps.commit.outputs.sha_short }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.13.0
        with:
          maven-version: 3.9.6

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      - name: Set commit_id output
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact to AWS S3
        run: aws s3 cp target/*.jar s3://bac-utils/build-artifacts/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Replace with your AWS region

  deploy:
    if: github.event_name == 'push' && github.event.head_commit.message != 'skip-deploy'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download artifact from AWS S3
        run: aws s3 cp s3://bac-utils/build-artifacts/*.jar ./target/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Replace with your AWS region

      - name: Docker build
        run: docker build --no-cache -t ${{ env.SERVICE_NAME }} .

      - name: Docker tag
        run: docker tag ${{ env.SERVICE_NAME }}:latest ${{ secrets.ECR_ENDPOINT }}:${{ needs.build.outputs.commit_id }}

      - name: Docker ECR login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_ENDPOINT }}

      - name: Docker push
        run: docker push ${{ secrets.ECR_ENDPOINT }}:${{ needs.build.outputs.commit_id }}
